version: '3'
services:
  app:
    container_name: pureplats
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:9090'
    depends_on:
      - mongodb
      - redis
    image: pureplats:latest
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
